language: java
jdk: oraclejdk8
install: true
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: JCw4qDdrxxpXSeI9UHUzMc2diNY6N1ejzYXe3ffu2eoopl9alBBt4JgxVQYObiHMKh88nfH7UICV8tz0RFpsyaOrEO7QxKDzmWbnPvIYkTGs/eHVkR1CuHbvPrNAGs3eKchTJtqtx4ezbLWGSYst4hc0He3PEvhagCAJJdxxR9qhW9M5ULp1EcsEH40gP0DHyDzA+JhiVXwrlVRxsobnodrOtedq1h1gEpJCdT6f/CQzV0+/JHzyVR4up1gvMRVF1z+iT8WSaSULwFK/rX/NBERO8e6BvmLyTamL969EA1z+c59RFq8vO1W5fEvM6F5AiVsL+v/P5Mtyw9XAHW/aQ4ICx6mYeUU5W+2m7d0T6uPz+p9FV8zk5PZXWBcgiwHwb/aUJESYcz5i2u5TSm5ydWnK7qzaN3LJB2Iksve5buLBnCA4ybavfdvyBq7FJUs73zPMUr45i2fp+MqLa0oyuRTqse6mn0tBGnzw3IAnoqBQ0TlocMzYZmpNVYNYVncRGjuTs1hnZZV4IQrx/MtMMKO6IQ+YSTSlmWJOxJPvYqbCKt2C6zocV8SAKFyGmqUwjdiAsCf76/xxS4C5e73hDMbQ9Xn2ZRoiOvt/pU+h8ByLuNgkk1U48PUa9AEmGSLGByZTvlrbL9vTKl719ntvsPG/pu50mYmowicInY9ZnVI=
